theme = "lynx"
title = "Dustin Smith"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Dustin Smith"
  headline = "Technical Communicator"
  image = "dls.jpg"
  links = [
     { email = "mailto:mail@dustinsmith.net" },
     { github = "https://github.com/dustinloflandsmith" },
     { gitlab = "https://gitlab.com/dustinloflandsmith" }, 
     { linkedin = "https://linkedin.com/in/dustinloflandsmith" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
